POST http://localhost:3333/survival-guide-store
Content-Type: application/json

{
	"title": "survival guide book",
	"description": "We hope you never need...   But, if for any reason you face the Chernobyl Residential Building, at Campeche, Brazil, this guide is the only chance to survive",
	"price": "$15"
}

###

GET http://localhost:3333/survival-guide-store

###

PUT http://localhost:3333/survival-guide-store/
Content-Type: application/json

{
	"title": "title test",
	"description": "This item might be you scared. But it is only necessary in extremely conditions. the instructions about when and how to use is on the survival guide book.",
	"price": "$600"
}

###

DELETE http://localhost:3333/survival-guide-store/